// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	CommandType_CREATE_USER              CommandType = 1
	CommandType_UPDATE_USER              CommandType = 2
	CommandType_DELETE_USER              CommandType = 3
	CommandType_DISABLE_USER             CommandType = 4
	CommandType_ENABLE_USER              CommandType = 5
	CommandType_SET_QUOTA                CommandType = 6
	CommandType_SYNC                     CommandType = 7
	// Hot-wires a relay node's local Xray process to forward one Route's
	// traffic to its exit (AddOutbound + AddRule), or a WireGuard/OpenVPN
	// subnet through the tun bridge -- see "Multi-Hop Relay Chaining" in
	// the architecture plan. Targets the relay node, not an end customer.
	CommandType_CONFIGURE_ROUTE CommandType = 8
	CommandType_REMOVE_ROUTE    CommandType = 9
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "CREATE_USER",
		2: "UPDATE_USER",
		3: "DELETE_USER",
		4: "DISABLE_USER",
		5: "ENABLE_USER",
		6: "SET_QUOTA",
		7: "SYNC",
		8: "CONFIGURE_ROUTE",
		9: "REMOVE_ROUTE",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED": 0,
		"CREATE_USER":              1,
		"UPDATE_USER":              2,
		"DELETE_USER":              3,
		"DISABLE_USER":             4,
		"ENABLE_USER":              5,
		"SET_QUOTA":                6,
		"SYNC":                     7,
		"CONFIGURE_ROUTE":          8,
		"REMOVE_ROUTE":             9,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_StatsBatch
	//	*AgentMessage_CommandAck
	//	*AgentMessage_StateSnapshot
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetStatsBatch() *StatsBatch {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StatsBatch); ok {
			return x.StatsBatch
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

func (x *AgentMessage) GetStateSnapshot() *StateSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StateSnapshot); ok {
			return x.StateSnapshot
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_StatsBatch struct {
	StatsBatch *StatsBatch `protobuf:"bytes,3,opt,name=stats_batch,json=statsBatch,proto3,oneof"`
}

type AgentMessage_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,4,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

type AgentMessage_StateSnapshot struct {
	StateSnapshot *StateSnapshot `protobuf:"bytes,5,opt,name=state_snapshot,json=stateSnapshot,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_StatsBatch) isAgentMessage_Payload() {}

func (*AgentMessage_CommandAck) isAgentMessage_Payload() {}

func (*AgentMessage_StateSnapshot) isAgentMessage_Payload() {}

// Hello must be the first message on every stream. Authentication is a
// self-signed, timestamped assertion rather than an interactive
// challenge-response: the agent signs node_id+timestamp+nonce with the
// Ed25519 private key it generated at enroll time, and the control plane
// verifies the signature against the public key it stored for that node
// during /enrollment/claim. The timestamp bounds replay -- the server
// rejects Hellos outside a small freshness window (see agent-gateway
// module) -- trading a round trip for simplicity, acceptable since this
// only authenticates the transport, not individual privileged actions.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix seconds when signed
	Nonce         string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`          // random per-connection, included in the signed payload
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`  // Ed25519 signature over `${node_id}.${timestamp}.${nonce}`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Hello) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Hello) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type Heartbeat struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent        float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent        float64                `protobuf:"fixed64,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *Heartbeat) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

type StatsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deltas        []*UsageDelta          `protobuf:"bytes,1,rep,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsBatch) Reset() {
	*x = StatsBatch{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsBatch) ProtoMessage() {}

func (x *StatsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsBatch.ProtoReflect.Descriptor instead.
func (*StatsBatch) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StatsBatch) GetDeltas() []*UsageDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

type UsageDelta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalUserId string                 `protobuf:"bytes,1,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	Protocol       string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BytesUp        uint64                 `protobuf:"varint,3,opt,name=bytes_up,json=bytesUp,proto3" json:"bytes_up,omitempty"`
	BytesDown      uint64                 `protobuf:"varint,4,opt,name=bytes_down,json=bytesDown,proto3" json:"bytes_down,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsageDelta) Reset() {
	*x = UsageDelta{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageDelta) ProtoMessage() {}

func (x *UsageDelta) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageDelta.ProtoReflect.Descriptor instead.
func (*UsageDelta) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UsageDelta) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *UsageDelta) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *UsageDelta) GetBytesUp() uint64 {
	if x != nil {
		return x.BytesUp
	}
	return 0
}

func (x *UsageDelta) GetBytesDown() uint64 {
	if x != nil {
		return x.BytesDown
	}
	return 0
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*ProtocolUserRef     `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StateSnapshot) GetUsers() []*ProtocolUserRef {
	if x != nil {
		return x.Users
	}
	return nil
}

type ProtocolUserRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalUserId string                 `protobuf:"bytes,1,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	Protocol       string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Version        int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProtocolUserRef) Reset() {
	*x = ProtocolUserRef{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolUserRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolUserRef) ProtoMessage() {}

func (x *ProtocolUserRef) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolUserRef.ProtoReflect.Descriptor instead.
func (*ProtocolUserRef) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ProtocolUserRef) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *ProtocolUserRef) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolUserRef) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Command
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

func (*ControlMessage_Command) isControlMessage_Payload() {}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=neoxify.agent.v1.CommandType" json:"type,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x10neoxify.agent.v1\"\xd3\x02\n" +
	"\fAgentMessage\x12/\n" +
	"\x05hello\x18\x01 \x01(\v2\x17.neoxify.agent.v1.HelloH\x00R\x05hello\x12;\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1b.neoxify.agent.v1.HeartbeatH\x00R\theartbeat\x12?\n" +
	"\vstats_batch\x18\x03 \x01(\v2\x1c.neoxify.agent.v1.StatsBatchH\x00R\n" +
	"statsBatch\x12?\n" +
	"\vcommand_ack\x18\x04 \x01(\v2\x1c.neoxify.agent.v1.CommandAckH\x00R\n" +
	"commandAck\x12H\n" +
	"\x0estate_snapshot\x18\x05 \x01(\v2\x1f.neoxify.agent.v1.StateSnapshotH\x00R\rstateSnapshotB\t\n" +
	"\apayload\"\x97\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\"|\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\x01R\n" +
	"memPercent\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\"B\n" +
	"\n" +
	"StatsBatch\x124\n" +
	"\x06deltas\x18\x01 \x03(\v2\x1c.neoxify.agent.v1.UsageDeltaR\x06deltas\"\x8c\x01\n" +
	"\n" +
	"UsageDelta\x12(\n" +
	"\x10external_user_id\x18\x01 \x01(\tR\x0eexternalUserId\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x19\n" +
	"\bbytes_up\x18\x03 \x01(\x04R\abytesUp\x12\x1d\n" +
	"\n" +
	"bytes_down\x18\x04 \x01(\x04R\tbytesDown\"[\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"H\n" +
	"\rStateSnapshot\x127\n" +
	"\x05users\x18\x01 \x03(\v2!.neoxify.agent.v1.ProtocolUserRefR\x05users\"q\n" +
	"\x0fProtocolUserRef\x12(\n" +
	"\x10external_user_id\x18\x01 \x01(\tR\x0eexternalUserId\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"R\n" +
	"\x0eControlMessage\x125\n" +
	"\acommand\x18\x01 \x01(\v2\x19.neoxify.agent.v1.CommandH\x00R\acommandB\t\n" +
	"\apayload\"o\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.neoxify.agent.v1.CommandTypeR\x04type\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\fR\vpayloadJson*\xc1\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCREATE_USER\x10\x01\x12\x0f\n" +
	"\vUPDATE_USER\x10\x02\x12\x0f\n" +
	"\vDELETE_USER\x10\x03\x12\x10\n" +
	"\fDISABLE_USER\x10\x04\x12\x0f\n" +
	"\vENABLE_USER\x10\x05\x12\r\n" +
	"\tSET_QUOTA\x10\x06\x12\b\n" +
	"\x04SYNC\x10\a\x12\x13\n" +
	"\x0fCONFIGURE_ROUTE\x10\b\x12\x10\n" +
	"\fREMOVE_ROUTE\x10\t2a\n" +
	"\fAgentGateway\x12Q\n" +
	"\tAgentSync\x12\x1e.neoxify.agent.v1.AgentMessage\x1a .neoxify.agent.v1.ControlMessage(\x010\x01B?Z=github.com/neoxify/neoxify-hub/agent/internal/controlplane/pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_goTypes = []any{
	(CommandType)(0),        // 0: neoxify.agent.v1.CommandType
	(*AgentMessage)(nil),    // 1: neoxify.agent.v1.AgentMessage
	(*Hello)(nil),           // 2: neoxify.agent.v1.Hello
	(*Heartbeat)(nil),       // 3: neoxify.agent.v1.Heartbeat
	(*StatsBatch)(nil),      // 4: neoxify.agent.v1.StatsBatch
	(*UsageDelta)(nil),      // 5: neoxify.agent.v1.UsageDelta
	(*CommandAck)(nil),      // 6: neoxify.agent.v1.CommandAck
	(*StateSnapshot)(nil),   // 7: neoxify.agent.v1.StateSnapshot
	(*ProtocolUserRef)(nil), // 8: neoxify.agent.v1.ProtocolUserRef
	(*ControlMessage)(nil),  // 9: neoxify.agent.v1.ControlMessage
	(*Command)(nil),         // 10: neoxify.agent.v1.Command
}
var file_agent_proto_depIdxs = []int32{
	2,  // 0: neoxify.agent.v1.AgentMessage.hello:type_name -> neoxify.agent.v1.Hello
	3,  // 1: neoxify.agent.v1.AgentMessage.heartbeat:type_name -> neoxify.agent.v1.Heartbeat
	4,  // 2: neoxify.agent.v1.AgentMessage.stats_batch:type_name -> neoxify.agent.v1.StatsBatch
	6,  // 3: neoxify.agent.v1.AgentMessage.command_ack:type_name -> neoxify.agent.v1.CommandAck
	7,  // 4: neoxify.agent.v1.AgentMessage.state_snapshot:type_name -> neoxify.agent.v1.StateSnapshot
	5,  // 5: neoxify.agent.v1.StatsBatch.deltas:type_name -> neoxify.agent.v1.UsageDelta
	8,  // 6: neoxify.agent.v1.StateSnapshot.users:type_name -> neoxify.agent.v1.ProtocolUserRef
	10, // 7: neoxify.agent.v1.ControlMessage.command:type_name -> neoxify.agent.v1.Command
	0,  // 8: neoxify.agent.v1.Command.type:type_name -> neoxify.agent.v1.CommandType
	1,  // 9: neoxify.agent.v1.AgentGateway.AgentSync:input_type -> neoxify.agent.v1.AgentMessage
	9,  // 10: neoxify.agent.v1.AgentGateway.AgentSync:output_type -> neoxify.agent.v1.ControlMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_StatsBatch)(nil),
		(*AgentMessage_CommandAck)(nil),
		(*AgentMessage_StateSnapshot)(nil),
	}
	file_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*ControlMessage_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
