// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGateway_AgentSync_FullMethodName = "/neoxify.agent.v1.AgentGateway/AgentSync"
)

// AgentGatewayClient is the client API for AgentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentSync is the single long-lived bidirectional stream an agent opens.
// The TCP connection is always initiated by the agent (never the control
// plane), so relay/exit nodes never need an inbound firewall hole; once
// open, messages flow both directions on the same stream. See
// docs/architecture.md for the full enrollment and reconciliation flow.
//
// Enrollment happens over plain HTTPS (POST /enrollment/claim) before this
// stream is ever opened -- that's where the agent trades a one-time admin-
// issued token for its identity being recorded against a Node row. This
// stream is purely for the ongoing authenticated channel once claimed.
type AgentGatewayClient interface {
	AgentSync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControlMessage], error)
}

type agentGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayClient(cc grpc.ClientConnInterface) AgentGatewayClient {
	return &agentGatewayClient{cc}
}

func (c *agentGatewayClient) AgentSync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[0], AgentGateway_AgentSync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_AgentSyncClient = grpc.BidiStreamingClient[AgentMessage, ControlMessage]

// AgentGatewayServer is the server API for AgentGateway service.
// All implementations must embed UnimplementedAgentGatewayServer
// for forward compatibility.
//
// AgentSync is the single long-lived bidirectional stream an agent opens.
// The TCP connection is always initiated by the agent (never the control
// plane), so relay/exit nodes never need an inbound firewall hole; once
// open, messages flow both directions on the same stream. See
// docs/architecture.md for the full enrollment and reconciliation flow.
//
// Enrollment happens over plain HTTPS (POST /enrollment/claim) before this
// stream is ever opened -- that's where the agent trades a one-time admin-
// issued token for its identity being recorded against a Node row. This
// stream is purely for the ongoing authenticated channel once claimed.
type AgentGatewayServer interface {
	AgentSync(grpc.BidiStreamingServer[AgentMessage, ControlMessage]) error
	mustEmbedUnimplementedAgentGatewayServer()
}

// UnimplementedAgentGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServer struct{}

func (UnimplementedAgentGatewayServer) AgentSync(grpc.BidiStreamingServer[AgentMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method AgentSync not implemented")
}
func (UnimplementedAgentGatewayServer) mustEmbedUnimplementedAgentGatewayServer() {}
func (UnimplementedAgentGatewayServer) testEmbeddedByValue()                      {}

// UnsafeAgentGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServer will
// result in compilation errors.
type UnsafeAgentGatewayServer interface {
	mustEmbedUnimplementedAgentGatewayServer()
}

func RegisterAgentGatewayServer(s grpc.ServiceRegistrar, srv AgentGatewayServer) {
	// If the following call panics, it indicates UnimplementedAgentGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGateway_ServiceDesc, srv)
}

func _AgentGateway_AgentSync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).AgentSync(&grpc.GenericServerStream[AgentMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_AgentSyncServer = grpc.BidiStreamingServer[AgentMessage, ControlMessage]

// AgentGateway_ServiceDesc is the grpc.ServiceDesc for AgentGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "neoxify.agent.v1.AgentGateway",
	HandlerType: (*AgentGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentSync",
			Handler:       _AgentGateway_AgentSync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
