"use client";

import { useState, useTransition } from "react";
import { toast } from "sonner";
import { updateProtocolConfig } from "./actions";
import type { ProtocolConfig } from "@/lib/types";
import { PROTOCOL_LABELS } from "@/lib/protocol-labels";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

/** Hints per protocol, shown inline so the values don't have to be
 * looked up elsewhere while filling this in. Only covers what an admin
 * supplies -- OpenVPN's CA is generated by the backend and preserved
 * across edits, so it deliberately isn't listed. */
const PARAM_HELP: Record<string, string> = {
  XRAY_VLESS_REALITY: "realityPublicKey, shortIds (array), dest, serverName",
  WIREGUARD: "serverPublicKey, endpoint, subnetCidr, and optionally dns",
  OPENVPN: "endpoint, and optionally proto (udp/tcp)",
  XRAY_VMESS: "protocol-specific connection parameters",
  // Vague help here is how a missing serverName went unnoticed until
  // every Trojan connection failed at the TLS handshake: the client
  // verifies the certificate against this name and cannot guess it.
  XRAY_TROJAN: "serverName -- the domain the node's certificate is issued for",
  XRAY_VLESS_TLS: "serverName -- the domain the node's certificate is issued for",
};

/** Editing exists because a config registered with wrong or missing
 * publicParamsJson was otherwise unfixable: delete is refused while
 * customers or routes still reference it, and there was no update path.
 *
 * Node and protocol aren't editable here -- both are baked into every
 * ProtocolUser already provisioned against this config, so changing them
 * would quietly break live connections. The backend rejects them too;
 * this just doesn't offer them. */
export function ProtocolConfigEditDialog({
  config,
  trigger,
}: {
  config: ProtocolConfig;
  trigger: React.ReactNode;
}) {
  const [open, setOpen] = useState(false);
  const [pending, startTransition] = useTransition();

  // Pretty-printed so a multi-key object is actually readable and
  // editable rather than one long line.
  const initialParams = JSON.stringify(config.publicParamsJson ?? {}, null, 2);

  function handleSubmit(formData: FormData) {
    const raw = String(formData.get("publicParamsJson") ?? "").trim();
    let publicParamsJson: Record<string, unknown> | undefined;
    if (raw) {
      try {
        publicParamsJson = JSON.parse(raw) as Record<string, unknown>;
      } catch {
        toast.error("Public params must be valid JSON");
        return;
      }
    }

    startTransition(async () => {
      const result = await updateProtocolConfig(config.id, {
        listenPort: Number(formData.get("listenPort")),
        publicParamsJson,
        isEnabled: formData.get("isEnabled") === "on",
      });

      if (result.ok) {
        toast.success("Protocol config updated");
        setOpen(false);
      } else {
        toast.error(result.error);
      }
    });
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Edit {PROTOCOL_LABELS[config.protocol]} config</DialogTitle>
        </DialogHeader>
        <form action={handleSubmit} className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <Label htmlFor="listenPort">Listen port</Label>
            <Input
              id="listenPort"
              name="listenPort"
              type="number"
              min={1}
              max={65535}
              defaultValue={config.listenPort}
              required
            />
            <p className="text-xs text-muted-foreground">
              Must match the port the engine actually listens on -- clients build their connection from
              this, not from the endpoint below.
            </p>
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="publicParamsJson">Public params (JSON)</Label>
            <textarea
              id="publicParamsJson"
              name="publicParamsJson"
              rows={8}
              defaultValue={initialParams}
              className="rounded-md border border-input bg-background px-3 py-2 font-mono text-xs shadow-xs outline-none focus-visible:ring-2 focus-visible:ring-ring/50"
            />
            <p className="text-xs text-muted-foreground">
              {PROTOCOL_LABELS[config.protocol]} needs {PARAM_HELP[config.protocol]}. Generated by the
              installer when the engine was set up on that node.
              {config.protocol === "OPENVPN"
                ? " Its CA and server certificate are managed here and kept across edits -- you don't need to include them."
                : ""}
            </p>
          </div>
          <label className="flex items-center gap-2 text-sm">
            <Checkbox name="isEnabled" defaultChecked={config.isEnabled} />
            Enabled
          </label>
          <p className="text-xs text-muted-foreground">
            Customers already provisioned on this config keep their existing credentials. If those were
            generated while these params were wrong, they need to switch server once to be re-provisioned.
          </p>
          <DialogFooter>
            <Button type="submit" disabled={pending}>
              {pending ? "Saving..." : "Save changes"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
