import { IsEmail, IsString, Length, MinLength } from "class-validator";

export class ResetPasswordCodeDto {
  @IsEmail()
  email!: string;

  /** Exactly six digits, as generated by forgotPassword(). Length is
   * fixed here so a caller cannot submit a long string and have it
   * compared character by character against a short stored value. */
  @IsString()
  @Length(6, 6)
  code!: string;

  @IsString()
  @MinLength(8)
  newPassword!: string;
}
