#!/usr/bin/env bash
# Installs and manages the main panel server (backend + admin panel +
# Postgres + Redis via Docker Compose, fronted by host nginx + Let's
# Encrypt). Assumes it's being run from inside a checked-out copy of the
# repo (installer/install.sh -> here), since docker compose needs the
# actual source tree (Dockerfiles, prisma schema, etc.) to build from.
set -euo pipefail

REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROD_COMPOSE="$REPO_ROOT/infra/docker-compose.prod.yml"
PROD_ENV="$REPO_ROOT/infra/.env"

install_docker_if_missing() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    echo "Docker is already installed."
    return
  fi
  echo "Installing Docker Engine + Compose plugin..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
}

install_nginx_certbot_if_missing() {
  if ! command -v nginx >/dev/null 2>&1; then
    echo "Installing nginx..."
    apt-get install -y -qq nginx
  fi
  if ! command -v certbot >/dev/null 2>&1; then
    echo "Installing certbot..."
    apt-get install -y -qq certbot python3-certbot-nginx
  fi
}

# Appends KEY=value to infra/.env only if KEY isn't already set there --
# never overwrites an existing value. This is what lets an
# already-deployed box pick up newly-required secrets (e.g. this
# installer version adding CUSTOMER_JWT_*) on a "Rebuild and restart"
# without disturbing anything already configured (a manually-filled-in
# STRIPE_SECRET_KEY, an admin-rotated JWT secret, etc).
ensure_env_key() {
  local key="$1" value="$2"
  if grep -q "^${key}=" "$PROD_ENV" 2>/dev/null; then
    return
  fi
  echo "${key}=${value}" >> "$PROD_ENV"
  echo "  added missing key to infra/.env: $key"
}

# Real bug fixed here (found while adding CUSTOMER_JWT_*): this used to be
# all-or-nothing -- generate everything on first install, or skip entirely
# if infra/.env already existed. That meant an already-deployed box never
# picked up secrets added by a later installer version (e.g. the
# CREDENTIALS_ENCRYPTION_KEY/ALERT_WEBHOOK_URL added when M11 shipped) --
# they'd only appear on a from-scratch reinstall. Now every expected key
# is checked individually and appended if missing, so re-running the
# installer (any menu action that calls this) heals an existing infra/.env
# instead of only ever fully creating or fully skipping it.
generate_panel_secrets() {
  if [[ ! -f "$PROD_ENV" ]]; then
    echo "Generating infra/.env..."
    install -d -m 755 "$(dirname "$PROD_ENV")"
    cat > "$PROD_ENV" <<'EOF'
# Generated by installer/lib/panel.sh. Random secrets below are
# auto-generated; external-service credentials are left blank for you to
# fill in, then re-run "Rebuild and restart".
EOF
    chmod 600 "$PROD_ENV"
  else
    echo "infra/.env already exists -- checking for any newly-required keys..."
  fi

  ensure_env_key "POSTGRES_PASSWORD" "$(openssl rand -hex 24)"
  ensure_env_key "JWT_ACCESS_SECRET" "$(openssl rand -hex 32)"
  ensure_env_key "JWT_REFRESH_SECRET" "$(openssl rand -hex 32)"
  ensure_env_key "JWT_ACCESS_TTL" "15m"
  ensure_env_key "JWT_REFRESH_TTL" "7d"
  ensure_env_key "CUSTOMER_JWT_ACCESS_SECRET" "$(openssl rand -hex 32)"
  ensure_env_key "CUSTOMER_JWT_REFRESH_SECRET" "$(openssl rand -hex 32)"
  ensure_env_key "CUSTOMER_JWT_ACCESS_TTL" "15m"
  ensure_env_key "CUSTOMER_JWT_REFRESH_TTL" "7d"
  ensure_env_key "CREDENTIALS_ENCRYPTION_KEY" "$(openssl rand -hex 32)"
  ensure_env_key "STRIPE_SECRET_KEY" ""
  ensure_env_key "STRIPE_WEBHOOK_SECRET" ""
  ensure_env_key "NOWPAYMENTS_API_KEY" ""
  ensure_env_key "NOWPAYMENTS_IPN_SECRET" ""
  ensure_env_key "ALERT_WEBHOOK_URL" ""
  # Optional, and blank is a working configuration -- the release lookups
  # behind /api/updates just run anonymously against GitHub's 60-per-hour
  # per-IP budget instead of 5,000. Worth filling in on a busy panel: a
  # failed lookup is what takes every download link down at once.
  ensure_env_key "GITHUB_API_TOKEN" ""
  # Generated rather than left blank: it is a secret of ours, not a
  # credential from somebody else's service, and the operator has no way to
  # invent a better one. The backend and the Discord bot both read this same
  # value, so generating it in one place is what makes them agree.
  ensure_env_key "INTEGRATIONS_SERVICE_TOKEN" "$(openssl rand -hex 32)"
  # The Discord bot is an opt-in compose profile. Blank keys so a fresh
  # infra/.env documents what to fill in without implying it is required.
  ensure_env_key "DISCORD_BOT_TOKEN" ""
  ensure_env_key "DISCORD_APPLICATION_ID" ""
  ensure_env_key "DISCORD_GUILD_ID" ""

  # Where this API answers from a customer's browser. Emails put links
  # here, so it has to be the public address including the /api prefix
  # nginx proxies under -- not the container's own port. Derived from the
  # panel's own domain, which is the same host by definition.
  local domain
  domain="$(get_panel_domain)"
  if [[ -n "$domain" ]]; then
    ensure_env_key "PUBLIC_API_URL" "https://$domain/api"
  else
    # Left empty rather than guessed: the verification email falls back to
    # its 6-digit code, which works regardless, instead of shipping a link
    # pointing at the wrong host.
    ensure_env_key "PUBLIC_API_URL" ""
  fi
}

configure_nginx_and_tls() {
  local domain="$1" email="$2"
  install -d -m 755 /var/www/html
  sed "s/__DOMAIN__/$domain/g" "$SCRIPT_DIR/assets/nginx-panel.conf.template" > "/etc/nginx/sites-available/neoxify-panel"
  ln -sf /etc/nginx/sites-available/neoxify-panel /etc/nginx/sites-enabled/neoxify-panel
  rm -f /etc/nginx/sites-enabled/default
  nginx -t
  systemctl reload nginx

  echo "Requesting a Let's Encrypt certificate for $domain..."
  if certbot --nginx -d "$domain" -m "$email" --agree-tos --non-interactive --redirect; then
    install_cert_sync_hook "$domain"
    sync_agent_gateway_certs "$domain"
    # The gRPC gateway only reads cert files at container startup, and the
    # backend was already started (without certs) earlier in
    # action_install_panel -- restart so it picks these up now.
    docker compose -f "$PROD_COMPOSE" --env-file "$PROD_ENV" restart backend
  else
    cat >&2 <<EOF

WARNING: certificate issuance failed. This almost always means the
domain doesn't resolve to this server's public IP yet, or port 80/443
isn't reachable from the internet. The panel is still up over plain
HTTP on port 80 for now, and the agent gRPC gateway stays disabled
(enrollment won't work) until this is fixed. Fix DNS and re-run:
  sudo certbot --nginx -d $domain -m $email --agree-tos --redirect
Then re-run this installer's "Rebuild and restart" to pick up the cert.
EOF
  fi
}

# The backend container runs as a non-root user and can't read certbot's
# privkey.pem (locked to root-only, 0600, for good reason). Copy both
# files into a location with relaxed-but-still-root-VPS-only permissions
# instead of bind-mounting /etc/letsencrypt directly -- see the comment
# in infra/docker-compose.prod.yml.
sync_agent_gateway_certs() {
  local domain="$1"
  install -d -m 755 /etc/neoxify/certs
  cp "/etc/letsencrypt/live/$domain/fullchain.pem" /etc/neoxify/certs/fullchain.pem
  cp "/etc/letsencrypt/live/$domain/privkey.pem" /etc/neoxify/certs/privkey.pem
  chmod 644 /etc/neoxify/certs/fullchain.pem /etc/neoxify/certs/privkey.pem
}

install_cert_sync_hook() {
  local domain="$1"
  install -d -m 755 /etc/letsencrypt/renewal-hooks/deploy
  cat > /etc/letsencrypt/renewal-hooks/deploy/neoxify-agent-gateway.sh <<EOF
#!/usr/bin/env bash
set -euo pipefail
install -d -m 755 /etc/neoxify/certs
cp "/etc/letsencrypt/live/$domain/fullchain.pem" /etc/neoxify/certs/fullchain.pem
cp "/etc/letsencrypt/live/$domain/privkey.pem" /etc/neoxify/certs/privkey.pem
chmod 644 /etc/neoxify/certs/fullchain.pem /etc/neoxify/certs/privkey.pem
EOF
  chmod 755 /etc/letsencrypt/renewal-hooks/deploy/neoxify-agent-gateway.sh
}

seed_first_admin() {
  echo
  read -r -p "Admin email for the first SUPERADMIN account: " admin_email
  local admin_password
  admin_password="$(openssl rand -base64 18 | tr -d '=+/' | cut -c1-20)"
  docker compose -f "$PROD_COMPOSE" --env-file "$PROD_ENV" exec -T \
    -e SEED_ADMIN_EMAIL="$admin_email" -e SEED_ADMIN_PASSWORD="$admin_password" \
    backend node dist-seed/seed.js

  cat <<EOF

  Admin login:
    email:    $admin_email
    password: $admin_password

  Save this now -- it will not be shown again. Change it after first
  login via PATCH /admins/:id.
EOF
}

action_install_panel() {
  require_root
  detect_os
  install_base_deps
  install_docker_if_missing
  install_nginx_certbot_if_missing
  generate_panel_secrets

  echo
  read -r -p "Domain name pointed at this server's IP (e.g. panel.example.com): " domain
  read -r -p "Email for Let's Encrypt renewal notices: " email

  # Recorded now, not at the end: if anything below fails partway through,
  # a re-run should land in the panel management menu (which can retry
  # the failed step) rather than repeat this entire interactive prompt
  # sequence and rebuild everything from scratch. The domain is persisted
  # too (not just used locally here) -- action_update_panel needs it on
  # every later "Rebuild and restart" to keep the agent gateway's certs
  # in sync, see get_panel_domain()/that action below.
  install -d -m 755 /etc/neoxify
  echo "panel" > /etc/neoxify/role
  echo "$domain" > /etc/neoxify/panel-domain

  echo "Building and starting the panel stack (this can take a few minutes on first run)..."
  docker compose -f "$PROD_COMPOSE" --env-file "$PROD_ENV" up -d --build

  echo "Waiting for the backend to become healthy..."
  local tries=0
  until curl -fsS http://127.0.0.1:4000/health >/dev/null 2>&1; do
    tries=$((tries + 1))
    if [[ $tries -gt 60 ]]; then
      echo "ERROR: backend did not become healthy in time. Check: docker compose -f $PROD_COMPOSE logs backend" >&2
      exit 1
    fi
    sleep 2
  done

  configure_nginx_and_tls "$domain" "$email"
  seed_first_admin
  install_backup_cron

  echo
  echo "Panel installed. Visit: https://$domain"
  echo "Daily backups are scheduled for 3am via /etc/cron.d/neoxify-backup (see docs/backup-restore.md)."

  # Said here, at the end, because it is the one remaining thing this
  # script cannot do for you and the way it fails is genuinely baffling.
  #
  # Most providers attach a firewall permitting only 22/80/443. The panel
  # is then perfect in a browser while every node sits PENDING forever,
  # because agents speak gRPC on 50051 and nothing else in the product
  # uses that port -- so nothing else looks wrong. Measured on a Hetzner
  # box during a migration: 80 and 443 reachable, 50051 dropped, with an
  # identically-configured host elsewhere serving it fine.
  cat <<PORTS

  ---------------------------------------------------------------
  One thing left, and it is outside this server.

  If your provider has a cloud firewall (Hetzner, AWS, GCP, Oracle,
  Vultr and others attach one by default), open inbound TCP 50051.

    22    SSH
    80    Let's Encrypt renewals and the HTTPS redirect
    443   panel and API
    50051 agent gRPC   <-- the one that is usually missed

  Without 50051 the panel works and every node stays PENDING with no
  visible error. Ports 3000 and 4000 bind to localhost on purpose and
  must NOT be opened.
  ---------------------------------------------------------------
PORTS
}

# Real bug found live (2026-07-24): a box whose original install's TLS
# step never ran to completion (or whose /etc/neoxify/certs was lost some
# other way -- disk migration, manual cleanup, anything) had a perfectly
# healthy panel over HTTPS while the agent gRPC gateway silently refused
# to start (AgentGatewayService deliberately won't run in plaintext in
# production) -- every node showed PENDING with lastHeartbeatAt: null
# forever, no error visible anywhere except the backend's own logs. Since
# action_update_panel didn't re-run the same sync_agent_gateway_certs()
# step that only ever happened once, during the original install, this
# had to be fixed by hand on the live box. Reads the domain back from
# /etc/neoxify/panel-domain (written by action_install_panel since this
# fix); falls back to parsing nginx's own config for boxes that predate
# that file (like the one this bug was actually found on), and persists
# it there for next time.
get_panel_domain() {
  if [[ -f /etc/neoxify/panel-domain ]]; then
    cat /etc/neoxify/panel-domain
    return
  fi
  # Explicit `|| true`: under `set -o pipefail` (this script's default), a
  # genuine no-match from grep (exit 1) would otherwise abort the whole
  # caller (action_update_panel) via `set -e` -- "couldn't find a domain"
  # must be a normal, handled outcome here, not a fatal error.
  local domain
  domain="$( { grep -m1 -oP 'server_name\s+\K[^;]+' /etc/nginx/sites-available/neoxify-panel 2>/dev/null || true; } | awk '{print $1}')"
  if [[ -n "$domain" ]]; then
    echo "$domain" > /etc/neoxify/panel-domain
    echo "$domain"
  fi
}

action_update_panel() {
  require_root
  generate_panel_secrets

  local domain
  domain="$(get_panel_domain)"
  if [[ -n "$domain" && -f "/etc/letsencrypt/live/$domain/fullchain.pem" ]]; then
    sync_agent_gateway_certs "$domain"
  else
    echo "WARNING: couldn't determine this panel's domain (or no Let's Encrypt cert found for it) -- skipping the agent gateway cert re-sync. If Nodes are stuck PENDING with no heartbeat, this is almost certainly why; see \"Agent gRPC gateway TLS\" in docs/architecture.md." >&2
  fi

  echo "Pulling latest source changes is up to you (git pull); rebuilding and restarting containers now..."
  docker compose -f "$PROD_COMPOSE" --env-file "$PROD_ENV" up -d --build
}

action_status_panel() {
  docker compose -f "$PROD_COMPOSE" --env-file "$PROD_ENV" ps
  echo
  docker compose -f "$PROD_COMPOSE" --env-file "$PROD_ENV" logs --tail 50
}

action_seed_admin_panel() {
  require_root
  seed_first_admin
}

install_backup_cron() {
  install -d -m 755 /etc/cron.d
  cat > /etc/cron.d/neoxify-backup <<EOF
# Daily panel backup (DB + TLS certs + infra/.env) -- see
# infra/scripts/backup.sh and docs/backup-restore.md.
0 3 * * * root $REPO_ROOT/infra/scripts/backup.sh >> /var/log/neoxify-backup.log 2>&1
EOF
  chmod 644 /etc/cron.d/neoxify-backup
}

action_backup_panel() {
  require_root
  "$REPO_ROOT/infra/scripts/backup.sh"
}

action_restore_panel() {
  require_root
  local default_dir="/var/backups/neoxify"
  echo
  echo "Backups in $default_dir:"
  ls -1t "$default_dir"/neoxify-backup-*.tar.gz 2>/dev/null || echo "  (none found)"
  echo
  read -r -p "Path to backup file to restore (blank = latest in $default_dir): " backup_path
  if [[ -z "$backup_path" ]]; then
    "$REPO_ROOT/infra/scripts/restore.sh" --latest "$default_dir"
  else
    "$REPO_ROOT/infra/scripts/restore.sh" "$backup_path"
  fi
}

action_uninstall_panel() {
  require_root
  read -r -p "This stops and removes the panel stack. Also delete the database volume? [y/N]: " purge
  local down_args=()
  [[ "${purge,,}" == "y" ]] && down_args+=("--volumes")
  docker compose -f "$PROD_COMPOSE" --env-file "$PROD_ENV" down "${down_args[@]}"
  rm -f /etc/nginx/sites-enabled/neoxify-panel /etc/nginx/sites-available/neoxify-panel
  systemctl reload nginx || true
  rm -f /etc/neoxify/role /etc/neoxify/panel-domain /etc/cron.d/neoxify-backup
  echo "Panel stack stopped. infra/.env, the repo checkout, and /var/backups/neoxify were left in place."
}

print_panel_menu() {
  cat <<'EOF'

  Neoxify Panel Server
  ------------------------
  1) View status / logs
  2) Rebuild and restart (after a git pull)
  3) Seed another admin account
  4) Backup now
  5) Restore from backup
  6) Uninstall
  7) Exit

EOF
}

run_panel_menu() {
  while true; do
    print_panel_menu
    read -r -p "Choose an option [1-7]: " choice
    case "$choice" in
      1) action_status_panel ;;
      2) action_update_panel ;;
      3) action_seed_admin_panel ;;
      4) action_backup_panel ;;
      5) action_restore_panel ;;
      6) action_uninstall_panel ;;
      7) exit 0 ;;
      *) echo "Invalid option: $choice" ;;
    esac
  done
}
