import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  describeEndpoint,
  httpAllowList,
  matchesCapabilityGlob,
} from "@shared/lib/capability-glob";

/** The same assertion the desktop client makes, about the mobile
 * client's own capability file.
 *
 * The desktop test carries the history: an endpoint shipped with no
 * matching glob, the HTTP plugin refused every request to it before it
 * left the device, the app fell back to a domain blocked in Iran, and a
 * new customer there could not register. It happened twice -- the second
 * time with a test in place, because it was looking at the compiled-in
 * list while the addresses customers actually use had moved into the
 * signed bundle.
 *
 * Both clients read that bundle and both have their own
 * capabilities/default.json, generated by the same script from the same
 * seed. Only one of them was checked. This is the other.
 *
 * The file under test is generated, not committed: `pretest` runs
 * apply-capability-scope.mjs first, which is also what a build does. The
 * committed form carries placeholders only, because a production host in
 * this repository is what docs/node-address-hygiene.md forbids.
 */
describe("mobile API endpoints are within the HTTP capability scope", () => {
  const capability = JSON.parse(
    readFileSync(new URL("../../src-tauri/capabilities/default.json", import.meta.url), "utf8"),
  );
  const allowed = httpAllowList(capability);

  it("declares an http:default allow list at all", () => {
    expect(allowed, "no http:default permission -- every request would be denied").toBeTruthy();
  });

  it("permits every endpoint the shipped bundle carries", () => {
    const seed = JSON.parse(
      readFileSync(
        new URL("../../../desktop-windows/src/lib/seed-bundle.json", import.meta.url),
        "utf8",
      ),
    ) as { payload?: string };
    // A placeholder seed ships no endpoints, so there is nothing to
    // permit. That is the ordinary state on a fresh checkout with no
    // network, and must not fail the suite.
    if (!seed.payload) return;
    const bundle = JSON.parse(Buffer.from(seed.payload, "base64").toString("utf8")) as {
      endpoints: { url: string }[];
    };
    expect(bundle.endpoints.length).toBeGreaterThan(0);
    bundle.endpoints.forEach((endpoint, index) => {
      const probe = endpoint.url + "/customer/me";
      expect(
        (allowed ?? []).some((entry) => matchesCapabilityGlob(entry.url, probe)),
        // By index and port, never by address: this repository is public
        // and so are its CI logs. See describeEndpoint.
        describeEndpoint(endpoint.url, index) +
          " is not covered by any entry in capabilities/default.json",
      ).toBe(true);
    });
  });

  /** A glob loose enough to match anything would make the check above
   * pass while removing the protection it is checking for. */
  it("does not permit an unrelated host", () => {
    const probe = "https://example.com/customer/me";
    expect((allowed ?? []).some((entry) => matchesCapabilityGlob(entry.url, probe))).toBe(false);
  });
});
