import { IsIP, IsOptional, IsString } from "class-validator";

export class ClaimEnrollmentDto {
  @IsString()
  token!: string;

  /** Base64-encoded raw 32-byte Ed25519 public key generated by the agent. */
  @IsString()
  publicKey!: string;

  @IsOptional()
  @IsString()
  agentVersion?: string;

  @IsOptional()
  @IsIP()
  publicIp?: string;
}
