-- Which Routes a plan may be served by, chosen per plan.
--
-- Until now a plan's routes were implied: every enabled Route whose
-- entry protocol the plan allowed, on the correct side of the
-- relay/direct split. That is the right default and stays the default --
-- but it offers no way to sell, say, a cheap tier on two locations and a
-- dearer one on all of them, and no way to keep a node out of a plan
-- without disabling it for everybody.
--
-- AN EMPTY SELECTION MEANS NO RESTRICTION. This table starts empty, so
-- every existing plan keeps exactly today's behaviour and no live
-- subscription changes -- the same property the relayOnly migration was
-- careful to have. It also means a Route added later reaches every
-- unrestricted plan on its own, with nobody editing anything.
--
-- Non-empty narrows and never widens: relayOnly and protocolsAllowed
-- still apply on top, so selecting a direct route on a relay-only plan
-- grants nothing. Picking routes is a way to serve less than the policy
-- permits, not a way around it.
--
-- Generated by `prisma migrate diff --from-empty --to-schema-datamodel`
-- rather than written by hand: the implicit-m2m table name, the A/B
-- column ordering (alphabetical by model, so A is Route and B is
-- SubscriptionPlan) and the index names are Prisma's own convention, and
-- getting any of them wrong produces a schema that migrates cleanly and
-- then fails at the first query.
CREATE TABLE "_PlanAllowedRoutes" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL
);

CREATE UNIQUE INDEX "_PlanAllowedRoutes_AB_unique" ON "_PlanAllowedRoutes"("A", "B");

CREATE INDEX "_PlanAllowedRoutes_B_index" ON "_PlanAllowedRoutes"("B");

-- CASCADE on both sides: a row here is only a link, so when either end
-- is deleted the link is meaningless. Without this, deleting a Route
-- would fail on a foreign key from a table the admin never sees.
ALTER TABLE "_PlanAllowedRoutes" ADD CONSTRAINT "_PlanAllowedRoutes_A_fkey" FOREIGN KEY ("A") REFERENCES "routes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "_PlanAllowedRoutes" ADD CONSTRAINT "_PlanAllowedRoutes_B_fkey" FOREIGN KEY ("B") REFERENCES "subscription_plans"("id") ON DELETE CASCADE ON UPDATE CASCADE;
