"""Splits the gomobile .aar into the pieces Gradle will accept.

An Android library module cannot depend on a local .aar. Gradle refuses
outright, and it is right to: the nested archive's classes and resources
would not be packaged into the library's own .aar, so the result would
build and then fail at runtime with a missing class. The pieces are all
supported on their own -- a plain .jar as a file dependency, the native
library through jniLibs, and the ProGuard rules as consumer rules.

That third piece is the one whose absence broke a release. gomobile's
bindings are reached from native code by name, and release builds
minify, so with the rules dropped R8 renamed the very classes
libgojni.so looks up and the app died the moment anything touched the
VPN plugin. Debug builds do not minify, which is exactly why it got
past every check and reached a customer. Copying all three is the point
of this script existing rather than a couple of unzip calls.
"""

import pathlib
import sys
import zipfile

def abi_in(archive: zipfile.ZipFile) -> str:
    """Whichever ABI gomobile actually built, read from the archive.

    Hardcoded to arm64-v8a before, which meant an x86_64 build failed
    here with a KeyError naming a path that was never going to exist.
    The archive already knows the answer, so asking it removes a second
    place that has to agree with XRAY_AAR_TARGET.
    """
    abis = sorted({
        name.split("/")[1]
        for name in archive.namelist()
        if name.startswith("jni/") and name.endswith("/libgojni.so")
    })
    if len(abis) != 1:
        raise SystemExit(f"expected exactly one ABI in {archive.filename}, found {abis}")
    return abis[0]

HEADER = """# Generated by scripts/unpack-xray-aar.py from the gomobile .aar's own
# proguard.txt. Do not edit by hand.
#
# gomobile's bindings are looked up from native code by name, so R8
# renaming them makes libgojni.so fail at runtime. That shipped in
# android-v0.2.1, where the app closed itself the moment it read VPN
# status, and only in release builds because debug does not minify.
"""


def main() -> int:
    aar, libs = sys.argv[1], pathlib.Path(sys.argv[2])
    with zipfile.ZipFile(aar) as archive:
        ABI = abi_in(archive)
        # Stale ABIs would otherwise linger from an earlier build and be
        # packaged alongside the new one.
        for old in (libs / "jni").glob("*"):
            if old.is_dir() and old.name != ABI:
                for f in old.iterdir():
                    f.unlink()
                old.rmdir()
        (libs / "jni" / ABI).mkdir(parents=True, exist_ok=True)
        (libs / "xray-classes.jar").write_bytes(archive.read("classes.jar"))
        (libs / "jni" / ABI / "libgojni.so").write_bytes(archive.read(f"jni/{ABI}/libgojni.so"))
        # Taken from the archive rather than retyped, so they stay correct
        # if gomobile's output ever changes.
        rules = archive.read("proguard.txt").decode()

    (libs.parent / "consumer-rules.pro").write_text(HEADER + rules, encoding="utf-8")
    print(f"unpacked xray-classes.jar, jni/{ABI}/libgojni.so and consumer-rules.pro")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
