"""Splits the gomobile .aar into the pieces Gradle will accept.

An Android library module cannot depend on a local .aar. Gradle refuses
outright, and it is right to: the nested archive's classes and resources
would not be packaged into the library's own .aar, so the result would
build and then fail at runtime with a missing class. The pieces are all
supported on their own -- a plain .jar as a file dependency, the native
library through jniLibs, and the ProGuard rules as consumer rules.

That third piece is the one whose absence broke a release. gomobile's
bindings are reached from native code by name, and release builds
minify, so with the rules dropped R8 renamed the very classes
libgojni.so looks up and the app died the moment anything touched the
VPN plugin. Debug builds do not minify, which is exactly why it got
past every check and reached a customer. Copying all three is the point
of this script existing rather than a couple of unzip calls.
"""

import pathlib
import sys
import zipfile

def abis_in(archive: zipfile.ZipFile) -> list[str]:
    """Every ABI gomobile built, read from the archive.

    Hardcoded to arm64-v8a originally, which meant an x86_64 build
    failed here with a KeyError naming a path that was never going to
    exist. Then it read the ABI from the archive but insisted on
    exactly one, which meant `XRAY_AAR_TARGET=android/arm64,android/amd64`
    -- a perfectly ordinary gomobile invocation -- was refused outright.

    Both restrictions were the same mistake in different clothes: the
    archive already knows the answer, and there is no reason to accept
    only one of it. A multi-ABI build is what a released APK wants
    anyway, because an x86_64 device given an arm64-only library gets a
    dlopen failure at connect time and silently falls back to another
    protocol -- observed on 2026-08-11, where every Xray route on an
    x86_64 emulator died with `library "libgojni.so" not found`.
    """
    abis = sorted({
        name.split("/")[1]
        for name in archive.namelist()
        if name.startswith("jni/") and name.endswith("/libgojni.so")
    })
    if not abis:
        raise SystemExit(f"no jni/*/libgojni.so found in {archive.filename}")
    return abis


HEADER = """# Generated by scripts/unpack-xray-aar.py from the gomobile .aar's own
# proguard.txt. Do not edit by hand.
#
# gomobile's bindings are looked up from native code by name, so R8
# renaming them makes libgojni.so fail at runtime. That shipped in
# android-v0.2.1, where the app closed itself the moment it read VPN
# status, and only in release builds because debug does not minify.

# Exception class names survive minification, so a failure with no
# message says what it was rather than what R8 renamed it to.
#
# Without this the plugin's `e.message ?: e.toString()` fallback sent
# the minified class name to the telemetry, and a real WireGuard
# failure was recorded as `{"protocol":"Fast","result":"v1.b"}`. That
# is indistinguishable from noise, in exactly the reports that exist
# because a customer could not connect and nobody could see why.
#
# -keepnames, not -keep: only the names are preserved, so the classes
# are still shrunk and their members still renamed.
-keepnames class * extends java.lang.Throwable
"""


def main() -> int:
    aar, libs = sys.argv[1], pathlib.Path(sys.argv[2])
    with zipfile.ZipFile(aar) as archive:
        abis = abis_in(archive)
        # Stale ABIs would otherwise linger from an earlier build and be
        # packaged alongside the new one -- which is worse than it
        # sounds, because the wrong-architecture library is found and
        # then fails to load rather than being absent.
        for old in (libs / "jni").glob("*"):
            if old.is_dir() and old.name not in abis:
                for f in old.iterdir():
                    f.unlink()
                old.rmdir()
        (libs / "xray-classes.jar").write_bytes(archive.read("classes.jar"))
        for abi in abis:
            (libs / "jni" / abi).mkdir(parents=True, exist_ok=True)
            (libs / "jni" / abi / "libgojni.so").write_bytes(archive.read(f"jni/{abi}/libgojni.so"))
        # Taken from the archive rather than retyped, so they stay correct
        # if gomobile's output ever changes.
        rules = archive.read("proguard.txt").decode()

    (libs.parent / "consumer-rules.pro").write_text(HEADER + rules, encoding="utf-8")
    print("unpacked xray-classes.jar, consumer-rules.pro and "
          + ", ".join(f"jni/{abi}/libgojni.so" for abi in abis))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
