# Generated by scripts/unpack-xray-aar.py from the gomobile .aar's own
# proguard.txt. Do not edit by hand.
#
# gomobile's bindings are looked up from native code by name, so R8
# renaming them makes libgojni.so fail at runtime. That shipped in
# android-v0.2.1, where the app closed itself the moment it read VPN
# status, and only in release builds because debug does not minify.
-keep class go.** { *; }
-keep class neoxifyxray.** { *; }
